version: '3.5'

services:
    redis:
        image: redis:6.2
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=postgres
    backend:
        build: ./example-backend
        ports:
            - 8080:8080
        depends_on:
            - db
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=postgres
    frontend:
        build: ./example-frontend
        ports:
            - 5000:5000
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80