version: '3.5'

services:
    frontend:
        build: ./frontend
        ports: 
            - 3000:3000
    backend: 
        build: ./backend
        ports:
            - 5000:5000
        volumes:
            - model:/src/model
        depends_on:
            - training
    training:
        build: ./training
        volumes:
            - model:/src/model
            - imgs:/src/imgs
            - data:/src/data
volumes:
    model:
    imgs:
    data: